@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-20 04:21
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=Blackline-Browser"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMjAgMDQ6MjENCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9QmxhY2tsaW5lLUJy
        echo b3dzZXIiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPWZpbGUiDQpzZXQg
        echo IkFQUF9FTlRSWT1zcmNcbWFpbi5weSINCnNldCAiUlVOTkVSX0FSR1M9Ig0KDQpzZXQgIlBZPSVD
        echo RCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIg
        echo KA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQWSUiDQogICAgZWNo
        echo by4NCiAgICBlY2hvIEZpeCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZf
        echo RElSJSINCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIiAtbSBwaXAg
        echo aW5zdGFsbCAtLXVwZ3JhZGUgcGlwDQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0
        echo aG9uLmV4ZSIgLW0gcGlwIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVjaG8uDQog
        echo ICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJmaWxl
        echo IiBpZiBub3QgZXhpc3QgIiVBUFBfRU5UUlklIiAoDQogICAgZWNobyBbRVJST1JdIEVudHJ5IGZp
        echo bGUgbm90IGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgZWNobyBFZGl0IHJ1bi5iYXQgb3IgcnVu
        echo IHdpdGggdGhlIGNvcnJlY3QgZW50cnkgZmlsZS4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0K
        echo KQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBSVU4iDQplY2hvID09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUnVubmlu
        echo ZyA6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNobyAgUHl0aG9uICA6
        echo ICVQWSUNCmVjaG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQ
        echo X0VOVFJZJQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAl
        echo UlVOTkVSX0FSR1MlDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0Kc2V0ICJFWElUQ09ERT0wIg0KDQppZiAv
        echo SSAiJUVOVFJZX01PREUlIj09Im1vZHVsZSIgKA0KICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAl
        echo Kg0KKSBlbHNlIGlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiAoDQogICAgaWYgZGVmaW5l
        echo ZCBSVU5ORVJfQVJHUyAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAhUlVOTkVSX0FS
        echo R1MhICUqDQogICAgKSBlbHNlICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICUqDQog
        echo ICAgKQ0KKSBlbHNlICgNCiAgICAiJVBZJSIgIiVBUFBfRU5UUlklIiAlKg0KKQ0KDQpzZXQgIkVY
        echo SVRDT0RFPSFFUlJPUkxFVkVMISINCg0KZWNoby4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9jZXNzIGV4
        echo aXRlZCB3aXRoIGNvZGU6ICFFWElUQ09ERSENCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAhRVhJ
        echo VENPREUhDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMjAgMDQ6MjENCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTIw
        echo IDA0OjIxDQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9QmxhY2tsaW5lLUJyb3dzZXIiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJBQ1RJ
        echo VkFURT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xhY3RpdmF0ZS5iYXQiDQoNCmlmIG5vdCBleGlz
        echo dCAiJUFDVElWQVRFJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdhcyBub3QgZm91
        echo bmQ6DQogICAgZWNobyAgICAgICAgICIlQUNUSVZBVEUlIg0KICAgIGVjaG8uDQogICAgZWNobyBD
        echo cmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJ
        echo UiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBS
        echo T0pFQ1RfTkFNRSUgLSBWRU5WIFNIRUxMIg0KY2FsbCAiJUFDVElWQVRFJSINCg0KZWNobyA9PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0N
        echo CmVjaG8gIFByb2plY3Qgc2hlbGwgYWN0aXZhdGVkDQplY2hvICBQcm9qZWN0OiAiJUNEJSINCmVj
        echo aG8gIFB5dGhvbiA6DQp3aGVyZSBweXRob24NCmVjaG8gIFR5cGUgImV4aXQiIHRvIGxlYXZlIHRo
        echo aXMgc2hlbGwuDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCmNtZCAvaw0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0yMCAwNDoyMQ0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1CbGFja2xp
        echo bmUtQnJvd3NlciINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElS
        echo JVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8g
        echo W0VSUk9SXSBMb2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hv
        echo IENyZWF0ZSBpdCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSIN
        echo CiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBT
        echo WU5DIg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KZWNobyAgU3luY2luZzogJVBST0pFQ1RfTkFNRSUNCmVjaG8gIFB5
        echo dGhvbiA6ICVQWSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQplY2hvLg0KDQplY2hvIFsxLzNdIFVwZ3JhZGluZyBwaXAu
        echo Li4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09DQoiJVBZJSIgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcA0KZWNoby4N
        echo Cg0KaWYgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiICgNCiAgICBlY2hvIFsyLzNdIEluc3RhbGxp
        echo bmcgZnJvbSByZXF1aXJlbWVudHMudHh0Li4uDQogICAgZWNobyA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCiAgICAiJVBZJSIgLW0g
        echo cGlwIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVjaG8uDQopIGVsc2UgKA0KICAg
        echo IGVjaG8gWzIvM10gU0tJUFBFRDogTm8gcmVxdWlyZW1lbnRzLnR4dCBmb3VuZC4NCiAgICBlY2hv
        echo ICAgICAgIENyZWF0ZSBvbmUgd2l0aDogcGlwLmJhdCBmcmVlemUgXj4gcmVxdWlyZW1lbnRzLnR4
        echo dA0KICAgIGVjaG8uDQopDQoNCmVjaG8gWzMvM10gRGVwZW5kZW5jeSBoZWFsdGggY2hlY2suLi4N
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQoiJVBZJSIgLW0gcGlwIGNoZWNrDQplY2hvLg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo U1lOQyBDT01QTEVURQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTIwIDA0OjIxDQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPUJsYWNrbGluZS1Ccm93
        echo c2VyIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0ICJB
        echo UFBfRU5UUlk9c3JjXG1haW4ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCnNldCAiUFk9JUNEJVwl
        echo VkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KZWNobyA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFBST0pFQ1Qg
        echo RE9DVE9SOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFByb2plY3QgOiAlQ0QlDQpl
        echo Y2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDogJUFQUF9FTlRSWSUN
        echo CmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAgIDogJVJVTk5FUl9B
        echo UkdTJQ0KZWNoby4NCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRkFJTF0gdmVu
        echo diBub3QgZm91bmQgYXQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBDcmVhdGUgaXQgd2l0
        echo aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAgcGF1c2UNCiAg
        echo ICBleGl0IC9iIDENCikNCg0KZWNobyBbT0tdIHZlbnYgZm91bmQ6ICIlUFklIg0KZWNoby4NCg0K
        echo ZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0NCmVjaG8gIFB5dGhvbiBFbnZpcm9ubWVudA0KZWNobyAtLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtYyAi
        echo aW1wb3J0IHN5czsgcHJpbnQoJ0V4ZWN1dGFibGUgOicsIHN5cy5leGVjdXRhYmxlKTsgcHJpbnQo
        echo J1ZlcnNpb24gICAgOicsIHN5cy52ZXJzaW9uLnNwbGl0KClbMF0pOyBwcmludCgnUHJlZml4ICAg
        echo ICA6Jywgc3lzLnByZWZpeCkiDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgcGlwIHZlcnNpb24N
        echo CmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlwIC0tdmVyc2lvbg0KZWNoby4NCg0KZWNobyAtLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVj
        echo aG8gIEluc3RhbGxlZCBQYWNrYWdlcw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgbGlzdA0KZWNo
        echo by4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0NCmVjaG8gIERlcGVuZGVuY3kgSGVhbHRoDQplY2hvIC0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUi
        echo IC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIEVudHJ5IFBvaW50IENoZWNr
        echo DQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJmaWxlIiAoDQogICAgaWYgZXhpc3Qg
        echo IiVBUFBfRU5UUlklIiAoDQogICAgICAgIGVjaG8gW09LXSBFbnRyeSBmaWxlIGZvdW5kOiAiJUFQ
        echo UF9FTlRSWSUiDQogICAgKSBlbHNlICgNCiAgICAgICAgZWNobyBbRkFJTF0gRW50cnkgZmlsZSBO
        echo T1QgZm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICApDQopIGVsc2UgKA0KICAgICIlUFklIiAtYyAi
        echo aW1wb3J0IGltcG9ydGxpYi51dGlsLCBzeXM7IG5hbWU9ciclQVBQX0VOVFJZJSc7IHNwZWM9aW1w
        echo b3J0bGliLnV0aWwuZmluZF9zcGVjKG5hbWUpOyBwcmludCgoJ1tPS10gTW9kdWxlIGZvdW5kOiAn
        echo IGlmIHNwZWMgZWxzZSAnW0ZBSUxdIE1vZHVsZSBOT1QgZm91bmQ6ICcpICsgbmFtZSk7IHN5cy5l
        echo eGl0KDAgaWYgc3BlYyBlbHNlIDEpIiAyPm51bA0KICAgIGlmIGVycm9ybGV2ZWwgMSBlY2hvIFtG
        echo QUlMXSBNb2R1bGUgaW1wb3J0IHRlc3QgZmFpbGVkLg0KICAgIGlmIC9JICIlRU5UUllfTU9ERSUi
        echo PT0icnVubmVyIiBlY2hvIFtJTkZPXSBSdW5uZXIgYXJnczogIiVSVU5ORVJfQVJHUyUiDQopDQpl
        echo Y2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgUHJvamVjdCBGaWxlcw0KZWNobyAtLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmlmIGV4aXN0
        echo ICJ1di5sb2NrIiAgICAgICAgICBlY2hvIFtPS10gICB1di5sb2NrIGZvdW5kDQppZiBleGlzdCAi
        echo cHlwcm9qZWN0LnRvbWwiICAgZWNobyBbT0tdICAgcHlwcm9qZWN0LnRvbWwgZm91bmQNCmlmIGV4
        echo aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtPS10gICByZXF1aXJlbWVudHMudHh0IGZvdW5k
        echo DQppZiBub3QgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW1dBUk5dIHJlcXVpcmVtZW50
        echo cy50eHQgbWlzc2luZw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIERPQ1RPUiBDT01QTEVURQ0K
        echo ZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMjAgMDQ6MjENCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1CbGFja2xpbmUtQnJvd3NlciINCnNldCAiVkVO
        echo Vl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUi
        echo DQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdh
        echo cyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8uDQogICAgcGF1
        echo c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gVEVTVCINCmVj
        echo aG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09DQplY2hvICBUZXN0aW5nOiAiJVBST0pFQ1RfTkFNRSUiDQplY2hvICBQeXRob24gOiAi
        echo JVBZJSINCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09DQplY2hvLg0KIiVQWSUiIC1tIHB5dGVzdCAtdiAlKg0Kc2V0ICJFWElU
        echo Q09ERT0lRVJST1JMRVZFTCUiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KaWYgIiVFWElUQ09ERSUiPT0i
        echo MCIgKA0KICAgIGVjaG8gIFRFU1RTIFBBU1NFRA0KKSBlbHNlICgNCiAgICBlY2hvICBURVNUUyBG
        echo QUlMRUQgIF4oZXhpdCBjb2RlOiAlRVhJVENPREUlXikNCikNCmVjaG8gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhp
        echo dCAvYiAlRVhJVENPREUlDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
